name = "mon"
version = "1.0.0"

description = "Parser combinators for Gleam, inspired by Rust's nom."
licences = ["MIT"]
repository = { type = "github", user = "kappq", repo = "mon" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
